name: "squirrel-re compile check"
description: "tries to compile a ttf2 vscript"

inputs:
  mods-directory:
    description: "the directory to check compile for"
    required: true
    

runs:
  using: 'composite'
  steps:
    - run: cd ${{ github.action_path }}
      shell: cmd
    - run: SquirrelStandalone.exe "${{ inputs.mods-directory }}"
      shell: cmd