name: "squirrel-re compile check"
description: "tries to compile Titanfall 2 vscripts using SquirrelStandalone"

inputs:
  mods-directory:
    description: "The directory containing the mods to be compiled"
    required: true
  native-json:
    description: "The path to the json file containing all of the native functions being added"
    required: true
  otherArgs:
    description: "Other arguments, passed directly."
    required: false
    

runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        SquirrelStandalone.exe "${{ inputs.mods-directory }}" "${{ inputs.native-json }}" ${{ inputs.constants }}
      shell: cmd
