name: "squirrel-re compile check"
description: "tries to compile Titanfall 2 vscripts using SquirrelStandalone"

inputs:
  mods-directory:
    description: "The directory containing the mods to be compiled"
    required: true
  native-json:
    description: "The path to the json file containing all of the native functions being added"
    required: true
  vanilla:
    description: "Whether or not to compile with the VANILLA const set to 1 or 0"
    required: true
    

runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        SquirrelStandalone.exe "${{ inputs.mods-directory }}" "${{ inputs.native-json }}" "${{ inputs.vanilla }}"
      shell: cmd
