name: "squirrel-re compile check"
description: "tries to compile Titanfall 2 vscripts using SquirrelStandalone"

inputs:
  mods-directory:
    description: "The directory containing the mods to be compiled"
    required: true
    

runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        SquirrelStandalone.exe "${{ inputs.mods-directory }}"
      shell: cmd