name: "squirre-re compile check"
description: "tries to compile a ttf2 vscript"

runs:
  using: "composite"
  steps:
    - name: "Check compile"
      shell: bash
      run: "./SquirrelStandalone.exe"
