name: build

on: [push, pull_request]

jobs:
  format:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Run SquirrelStandalone
        - run: |
          "SquirrelStandalone.exe"
        shell: cmd

